---
title: "BCCrimeTrends"
author: "Kitson Swann"
date: '2017-03-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(stringr)

bccrime <- read_csv("../data/BCCrimeData2006_2015.csv")

all_crime <- bccrime %>%
  gather(key = Year, value = Value, `2006`,`2007`,`2008`,`2009`,`2010`,`2011`,`2012`,`2013`,`2014`,`2015`)

all_crime$`POLICING JURISDICTION` <- str_trim(str_replace_all(all_crime$`POLICING JURISDICTION`, pattern = '[0-9,()]', replacement = ''))

write_csv(all_crime,"../results/clean_crime.csv")


```

```{r}

input_stat_chosen <- 'Homicide'
input_year_chosen <- c(2006,2015)
input_region_selection <- 'Metro Vancouver'
input_jurisdictions <- c('Burnaby Mun')


      sub_data <- all_crime %>%
        select(STATISTIC, Year, REGION, `POLICING JURISDICTION`, Value) %>% 
        filter(STATISTIC == input_stat_chosen) %>%
        filter(Year >= as.integer(input_year_chosen[1]) & 
                 Year <= as.integer(input_year_chosen[2]) &
                 REGION == input_region_selection &
                 `POLICING JURISDICTION`  %in% input_jurisdictions) %>% 
        group_by(`POLICING JURISDICTION`, Year) %>% 
        summarize(Value=sum(Value))
      
      sub_data


```

